services:
  h5ai:
    image: awesometic/h5ai:latest
    container_name: h5ai
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    ports:
      - 90:80/tcp
    volumes:
      - ./data:/config
      - /mnt/Downloads:/h5ai
    restart: unless-stopped
