keys:
  - &personal age1nn5xascw770dyjnga00ptpy3nuxuhunygajkekdaa7sjfx74msss63crpw
  - &apollo age1883ex3qm7gh9f5t90czvagslvna0wlt79nks5pqmy20jfy3z6qcqd8a0rq
  - &ares age1gjpkkr3vp8xaswzmnywl9zalkgja3v6y3eqy4rthk2nxdssvk3lq6gsfsl
  - &astra age1mchyxdcsrxqly8esmfa8d3urgq99kae25e6kn606v6dt6r7z7v7q8ezly5
  - &aurora age1yq2ksala2xds5jd626yqqt84uyuzetmknpyyemn7nuvgv4jdmy3s95ewwa
  - &orion age1shggmz7tt4uc0jucrn42gnu5mtwd7rmumw70k4xw0xj7wmps3yxqarmy97
  - &quasar age1tq6tucepu9pmqp5r6xhtj0lrzpa836ud3szzpt9nsn57cpxw9fksdw235r
  - &vortex age1xp8ekv8t7fuqgm8uet6sr9a308pgj6wpry4jwcr904rz8s8vyffs424xph
  - &zenith age17qlc0x0mltj3l2dqwag3dtf5jxzvftvmfkl5a386y3fsxdh49pgqrdqd7z
creation_rules:
  - key_groups:
      - age:
          - *personal
          - *apollo
          - *ares
          - *astra
          - *aurora
          - *orion
          - *vortex
          - *quasar
          - *zenith
