keys:
  - &cosmos age1c6cze3fjycgewldndd3tvkys67g59xc8prauvqwtjpdttzqe8upqalu72y
  - &nebula age1d67kp0xknjrtdg97w7kd5t3legh8adp5nngahmzx0smh09zlzytsrz4u5g
  - &nova age1pq4rcvfshnjvx25m78xspxsk90cp4nggw5s0s3chczjwwjk4fcss98r3rl
  - &trinity age1rst3fnsdqkj6uvmgtxxhj58kh4qfz38flre2hh409nzu65ntv5eqxksqnw
creation_rules:
  - path_regex: secrets/*
    key_groups:
      - age:
          - *cosmos
          - *nebula
          - *nova
          - *trinity
