# Generated by OrbStack.
{
  lib,
  config,
  namespace,
  ...
}:
with lib;
with lib.${namespace};
{
  # Add OrbStack CLI tools to PATH
  environment.shellInit = ''
    . /opt/orbstack-guest/etc/profile-early
    . /opt/orbstack-guest/etc/profile-late
  '';

  # Disable systemd-resolved
  services.resolved = disabled;
  environment.etc."resolv.conf".source = "/opt/orbstack-guest/etc/resolv.conf";

  # Faster DHCP - OrbStack uses SLAAC exclusively
  networking.dhcpcd.extraConfig = ''
    noarp
    noipv6
  '';

  # systemd
  systemd.services."systemd-oomd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-userdbd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-udevd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-timesyncd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-timedated".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-portabled".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-nspawn@".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-machined".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-localed".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-logind".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journald@".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journald".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journal-remote".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journal-upload".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-importd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-hostnamed".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-homed".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-networkd".serviceConfig.WatchdogSec =
    lib.mkIf config.systemd.network.enable 0;

  # ssh config
  programs.ssh.extraConfig = ''
    Include /opt/orbstack-guest/etc/ssh_config
  '';

  # indicate builder support for emulated architectures
  nix.settings.extra-platforms = [
    "x86_64-linux"
    "i686-linux"
  ];

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
            -----BEGIN CERTIFICATE-----
      MIICCzCCAbKgAwIBAgIQduCEvPb0YJI6uqaTc8oXLDAKBggqhkjOPQQDAjBmMR0w
      GwYDVQQKExRPcmJTdGFjayBEZXZlbG9wbWVudDEeMBwGA1UECwwVQ29udGFpbmVy
      cyAmIFNlcnZpY2VzMSUwIwYDVQQDExxPcmJTdGFjayBEZXZlbG9wbWVudCBSb290
      IENBMB4XDTI1MDMyMzE0MTIxOFoXDTM1MDMyMzE0MTIxOFowZjEdMBsGA1UEChMU
      T3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5lcnMgJiBTZXJ2
      aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9vdCBDQTBZMBMG
      ByqGSM49AgEGCCqGSM49AwEHA0IABMEGabZYf/4gil4lUoxbc/F3cbfib7xFmRQb
      Lll8HVuPnxRCYMoP/9tfKLEz6AMvHHI+U3+FfQnzWNAHrmzb8fejQjBAMA4GA1Ud
      DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQYXsQSgO981oWd
      RAzNOFYz3UTWnDAKBggqhkjOPQQDAgNHADBEAiA67eieknWem0yVQMKtTh8g5w+D
      +5Q/XqzCmtWuIzC84wIgVFUeGtZqz4hoNOzvZzF6twiKhcjSSGa4h0LOVr3VRv4=
      -----END CERTIFICATE-----

      -----BEGIN CERTIFICATE-----
      MIIDKDCCAhCgAwIBAgIUe33sVUWzHocg2QmJcI3RTnbUDyYwDQYJKoZIhvcNAQEL
      BQAwFDESMBAGA1UEAwwJKi5vcmIubGFiMB4XDTI1MDUwOTA5NDkxNloXDTI3MDgx
      MjA5NDkxNlowFDESMBAGA1UEAwwJKi5vcmIubGFiMIIBIjANBgkqhkiG9w0BAQEF
      AAOCAQ8AMIIBCgKCAQEAs45q5bjrUs5xpiD6PDdtYIlbTZm1xp2HaLwzTKG9AdHA
      xpVzqcx7JCUIA//2Yr/4SzAoU0ay6QYvYmmwS2BCR3oEVbIgtME1VnUIDBVK+dQB
      fspCgHSO5W8jRm48xdNt+bezlmq7k+CneRMuoJRcai9wJAW9i8AprHTxpU9N2Cit
      on1rIo+pFpuTdERFi4eI2LcUyZPoOTbzgDAJd8etyrg6Ep2bbVLvw39d+ENfDuqt
      dIGGJS1nfgOHEGuvYwLwfQs980D7pvcfy/91qPrfD3rDkxT4zLi0xZe24T6vVjhj
      EF5cNj+Aqa5i3NkjHPgWJlQhUnxhTu1Az4V+pI963wIDAQABo3IwcDAdBgNVHQ4E
      FgQUt49mluKON9DD67w+UAGxMd++/KwwHwYDVR0jBBgwFoAUt49mluKON9DD67w+
      UAGxMd++/KwwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHREEFjAUggkqLm9yYi5sYWKC
      B29yYi5sYWIwDQYJKoZIhvcNAQELBQADggEBAF/9MuOn75OzoKbUPQp7t8+aXxb+
      CGgk5jpnC73dEXebmkMJYG5fRicq3Ti9hbuhHjHLODffYqH0JBJqMK4s6ulubxCO
      r6rRucgoJkYTVOXaaUdP3eYVIEM+zG+qqvOkoLxnmTf8MROwC+gDEapFQpv3HoEV
      OAcIAD2eXeTiMXbZa0VI3JTqz+Mvcxzz9TWFY7WpI7KWrpbadUP5pmaPRSJ0ukpe
      m55LbqDukeFCr8Huoo9QDqP0fkzIFNYAW8R+zKA4ebpiUEf+8JClw/ffeNCbvSnm
      vJ5JMUNbUvylGuy1Ava+t/iAQ3AyoszZu41Mngay9Ji2kPUIp8sRTvKTZQE=
      -----END CERTIFICATE-----

      -----BEGIN CERTIFICATE-----
      MIIDKDCCAhCgAwIBAgIUe33sVUWzHocg2QmJcI3RTnbUDyYwDQYJKoZIhvcNAQEL
      BQAwFDESMBAGA1UEAwwJKi5vcmIubGFiMB4XDTI1MDUwOTA5NDkxNloXDTI3MDgx
      MjA5NDkxNlowFDESMBAGA1UEAwwJKi5vcmIubGFiMIIBIjANBgkqhkiG9w0BAQEF
      AAOCAQ8AMIIBCgKCAQEAs45q5bjrUs5xpiD6PDdtYIlbTZm1xp2HaLwzTKG9AdHA
      xpVzqcx7JCUIA//2Yr/4SzAoU0ay6QYvYmmwS2BCR3oEVbIgtME1VnUIDBVK+dQB
      fspCgHSO5W8jRm48xdNt+bezlmq7k+CneRMuoJRcai9wJAW9i8AprHTxpU9N2Cit
      on1rIo+pFpuTdERFi4eI2LcUyZPoOTbzgDAJd8etyrg6Ep2bbVLvw39d+ENfDuqt
      dIGGJS1nfgOHEGuvYwLwfQs980D7pvcfy/91qPrfD3rDkxT4zLi0xZe24T6vVjhj
      EF5cNj+Aqa5i3NkjHPgWJlQhUnxhTu1Az4V+pI963wIDAQABo3IwcDAdBgNVHQ4E
      FgQUt49mluKON9DD67w+UAGxMd++/KwwHwYDVR0jBBgwFoAUt49mluKON9DD67w+
      UAGxMd++/KwwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHREEFjAUggkqLm9yYi5sYWKC
      B29yYi5sYWIwDQYJKoZIhvcNAQELBQADggEBAF/9MuOn75OzoKbUPQp7t8+aXxb+
      CGgk5jpnC73dEXebmkMJYG5fRicq3Ti9hbuhHjHLODffYqH0JBJqMK4s6ulubxCO
      r6rRucgoJkYTVOXaaUdP3eYVIEM+zG+qqvOkoLxnmTf8MROwC+gDEapFQpv3HoEV
      OAcIAD2eXeTiMXbZa0VI3JTqz+Mvcxzz9TWFY7WpI7KWrpbadUP5pmaPRSJ0ukpe
      m55LbqDukeFCr8Huoo9QDqP0fkzIFNYAW8R+zKA4ebpiUEf+8JClw/ffeNCbvSnm
      vJ5JMUNbUvylGuy1Ava+t/iAQ3AyoszZu41Mngay9Ji2kPUIp8sRTvKTZQE=
      -----END CERTIFICATE-----

      -----BEGIN CERTIFICATE-----
      MIICCzCCAbKgAwIBAgIQduCEvPb0YJI6uqaTc8oXLDAKBggqhkjOPQQDAjBmMR0w
      GwYDVQQKExRPcmJTdGFjayBEZXZlbG9wbWVudDEeMBwGA1UECwwVQ29udGFpbmVy
      cyAmIFNlcnZpY2VzMSUwIwYDVQQDExxPcmJTdGFjayBEZXZlbG9wbWVudCBSb290
      IENBMB4XDTI1MDMyMzE0MTIxOFoXDTM1MDMyMzE0MTIxOFowZjEdMBsGA1UEChMU
      T3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5lcnMgJiBTZXJ2
      aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9vdCBDQTBZMBMG
      ByqGSM49AgEGCCqGSM49AwEHA0IABMEGabZYf/4gil4lUoxbc/F3cbfib7xFmRQb
      Lll8HVuPnxRCYMoP/9tfKLEz6AMvHHI+U3+FfQnzWNAHrmzb8fejQjBAMA4GA1Ud
      DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQYXsQSgO981oWd
      RAzNOFYz3UTWnDAKBggqhkjOPQQDAgNHADBEAiA67eieknWem0yVQMKtTh8g5w+D
      +5Q/XqzCmtWuIzC84wIgVFUeGtZqz4hoNOzvZzF6twiKhcjSSGa4h0LOVr3VRv4=
      -----END CERTIFICATE-----

    ''
  ];

  users.groups.orbstack.gid = 67278;
}
