version: "3.8"

volumes:
    overseerr_data: {}
services:
    overseerr:
        image: sctx/overseerr:latest
        container_name: overseerr
        environment:
            - LOG_LEVEL=debug
            - TZ=Asia/Kolkata
        ports:
            - 5055:5055
        volumes:
            - overseerr_data:/app/config
        restart: unless-stopped
