version: "3.8"

volumes:
    plex_data: {}

services:
    plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        ports:
            - 32400:32400
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker
            - PLEX_CLAIM= # optional
        volumes:
            - plex_data:/config
            - /mnt/Plex/Anime:/anime
            - /mnt/Plex/Movies:/movies
            - /mnt/Plex/Shows:/shows
        restart: unless-stopped
