version: "3.8"

volumes:
    qbittorrent_data: {}

services:
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
            - WEBUI_PORT=3000
        volumes:
            - qbittorrent_data:/config
            - /home/ubuntu/Downloads:/downloads
        ports:
            - 3000:3000
        restart: unless-stopped
