version: "3.8"

volumes:
    h5ai:
        external: true

networks:
    web:
        external: true

services:
    h5ai:
        image: awesometic/h5ai
        container_name: h5ai
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        networks:
            - web
        ports:
            - 80:80/tcp
        volumes:
            - h5ai:/config
            - /home/ubuntu/Downloads:/h5ai
        restart: always
