version: "3.8"

volumes:
  jellyfin:
    external: true

networks:
  web:
    external: true

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - jellyfin:/config
      - /mnt/Plex/Movies_4K:/movies
      - /mnt/Plex/Shows_4K:/shows
    ports:
      - 8096:8096
    restart: unless-stopped
