version: "3.8"

volumes:
    qbittorrent:
        external: true

networks:
    web:
        external: true

services:
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
            - WEBUI_PORT=5000
        networks:
            - web
        volumes:
            - qbittorrent:/config
            - /home/ubuntu/Downloads:/downloads
        ports:
            - 5000:5000
        restart: unless-stopped
