default_redirection_url: https://auth.yashgarg.dev/
default_2fa_method: webauthn
theme: auto

access_control:
  default_policy: deny
  rules:
    - domain: "auth.yashgarg.dev"
      policy: two_factor
      subject:
        - "group:cloudflare-admins" # Currently not supported by OIDC
      networks: "127.0.0.1"

identity_providers:
  oidc:
    access_token_lifespan: 30m
    authorize_code_lifespan: 1m
    id_token_lifespan: 30m
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: always
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
        - userinfo
      allowed_origins:
        - https://auth.yashgarg.dev
      allowed_origins_from_client_redirect_uris: false
    clients:
      - id: cloudflare
        description: Cloudflare Access
        secret: <OIDC Secret> #Shared with Cloudflare
        public: false
        authorization_policy: two_factor
        consent_mode: pre-configured
        pre_configured_consent_duration: "6M"
        redirect_uris:
          - https://yashg.cloudflareaccess.com/cdn-cgi/access/callback
        scopes:
          - openid
          - profile
          - email
          - groups # Currently not supported in Authelia V
        userinfo_signing_algorithm: RS256

log:
  level: "info"

server:
  disable_healthcheck: true

session:
  name: authelia_session
  domain: auth.yashgarg.dev
  same_site: strict
  expiration: 30m
  inactivity: 15m
  remember_me_duration: 30m

telemetry:
  metrics:
    enabled: true

totp:
  disable: true

webauthn:
  disable: false
  enable_passkey_login: true
  display_name: Authelia
  attestation_conveyance_preference: direct
  user_verification: required
  timeout: 60s
