services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=3000
      - TORRENTING_PORT=6881
    volumes:
      - qbit-data:/config
      - /mnt/media:/media
    ports:
      - 3000:3000
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
