services:
  mc-server:
    container_name: mc-server
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      SEED: 5063885805507972000
      EULA: "TRUE"
      TYPE: FABRIC
      MEMORY: 20G
      DIFFICULTY: NORMAL
      MOTD: Pixel Paradise
      ENFORCE_WHITELIST: "TRUE"
      WHITELIST_FILE: /extra/whitelist.json
      OPS_FILE: /extra/ops.json
      ONLINE_MODE: "FALSE"
      REMOVE_OLD_MODS: "TRUE"
      MAX_PLAYERS: 10
      USE_AIKAR_FLAGS: "TRUE"
      VANILLATWEAKS_SHARECODE: bmipN5,SLs3nU
      LOG_TIMESTAMP: "TRUE"
      TZ: Asia/Kolkata
      RCON_CMDS_STARTUP: /gamerule keepInventory true
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
      MODRINTH_PROJECTS: |-
        beautified-chat-server
        c2me-fabric
        fabric-api
        ferrite-core
        jade
        krypton
        leaves-us-in-peace
        lithium
        netherportalfix
        no-chat-reports
        scaffolding-drops-nearby
        skinrestorer
    volumes:
      - ./data:/data
      - ./extra:/extra
    restart: unless-stopped
