services:
  mc-server:
    container_name: mc-server
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
      - 81:8080
    environment:
      SEED: "-5584399987456711267"
      EULA: "TRUE"
      TYPE: FABRIC
      MEMORY: 16G
      DIFFICULTY: NORMAL
      ICON: /extra/icon.jpeg
      OVERRIDE_ICON: "TRUE"
      MOTD: "§l§cPixel Paradise§r"
      ENFORCE_WHITELIST: "TRUE"
      WHITELIST_FILE: /extra/whitelist.json
      OPS_FILE: /extra/ops.json
      ONLINE_MODE: "TRUE"
      REMOVE_OLD_MODS: "TRUE"
      MAX_PLAYERS: 2
      USE_AIKAR_FLAGS: "TRUE"
      VANILLATWEAKS_SHARECODE: bmipN5,SLs3nU
      LOG_TIMESTAMP: "TRUE"
      TZ: Asia/Kolkata
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
      MODRINTH_PROJECTS: |-
        beautified-chat-server
        c2me-fabric
        chunky
        fabric-api
        ferrite-core
        krypton
        leaves-us-in-peace
        lithium
        netherportalfix
        no-chat-reports
        pl3xmap
        scaffolding-drops-nearby
      RCON_CMDS_STARTUP: |-
        /gamerule keepInventory true
        /chunky radius 1000
        /chunky start
      RCON_CMDS_FIRST_CONNECT: |-
        /chunky pause
      RCON_CMDS_LAST_DISCONNECT: |-
        /save-all
        /chunky continue
    volumes:
      - ./data:/data
      - ./extra:/extra
    restart: unless-stopped
