services:
  glance:
    container_name: glance
    image: glanceapp/glance
    volumes:
      - ../glance/glance.yml:/app/glance.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    restart: unless-stopped
