services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - radarr-data:/config
      - /mnt/media/movies:/movies
      - /mnt/media:/media
    ports:
      - 7878:7878
    restart: unless-stopped
