add_newline = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[git_branch]
always_show_remote = true

[git_status]
ahead = "${count}"
diverged = "${ahead_count}${behind_count}"
behind = "${count}"
