#!/usr/bin/env bash

alias cls='clear'
alias gw='./gradlew'

if type bat &>/dev/null; then
    alias cat='bat'
fi

if type dust &>/dev/null; then
    alias du='dust'
fi

if type fastfetch &>/dev/null; then
    alias fetch='fastfetch'
fi

if type git &>/dev/null; then
    alias amend='git commit --amend'
    alias add='git add --all'
    alias st='git status'
    alias push='git push'
    alias fpush='git push --force-with-lease'
    alias pull='git pull'
    alias commit='git commit -m'
    alias rst='git reset; git restore .'
fi

if type nvim &>/dev/null; then
    export EDITOR='nvim'
fi

if type micro &>/dev/null; then
    alias m='micro'
fi

if type rg &>/dev/null; then
    alias grep='rg'
fi

if type xclip &>/dev/null; then
    alias xclip='xclip -selection c'
fi

if type zoxide &>/dev/null; then
    alias cd='z'
fi

if type kubectl &>/dev/null; then
    alias k='kubectl'
fi

if type kitty &>/dev/null; then
    alias s='kitten ssh'
fi

if type batman &>/dev/null; then
    alias man='batman'
fi

if type zellij &>/dev/null; then
    alias zj='zellij'
    alias zl='zellij --layout'
    alias zr='zellij run -d right -c --'
    alias zrf='zellij run -f -c --'
    alias zri='zellij run -d right -i -c --'
    alias zkill='zellij ka && zellij da'
fi

if type nh_darwin &>/dev/null; then
    alias nh='nh_darwin'
fi

if type just &>/dev/null; then
    alias j='just'
fi
