#!/usr/bin/env bash

alias cls='clear'
alias gw='./gradlew'

if type bat &> /dev/null; then
    alias cat='bat'
fi

if type zoxide &> /dev/null; then
    alias cd='z'
fi

if type git &> /dev/null; then
    alias amend='git commit --amend'
    alias add='git add --all'
    alias st='git status'
    alias push='git push'
    alias fpush='git push --force'
    alias pull='git pull'
    alias commit='git commit --all -m'
    alias rst='git reset; git restore .'
fi
