#!/usr/bin/env bash

[ -f "$HOME/.functions" ] && source "$HOME/.functions"
[ -f "$HOME/.aliases" ] && source "$HOME/.aliases"

[ -d "$HOME/.sdkman" ] && source "$HOME/.sdkman/bin/sdkman-init.sh"

[ -d "$HOME/Android/Sdk" ] && export ANDROID_HOME="$HOME/Android/Sdk"

[ -d "$HOME/Android/Flutter" ] && export PATH="$HOME/Android/Flutter/bin"

for dir in "platform-tools" "cmdline-tools/latest/bin"; do
  [ -d "$ANDROID_HOME/$dir" ] && export PATH="$ANDROID_HOME/$dir:$PATH"
done
