services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./data:/config
      - /mnt/Media/Shows:/shows
      - /mnt/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
