# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    extraModulePackages = [ ];
    initrd.availableKernelModules = [ ];
    initrd.kernelModules = [ ];
    kernelModules = [ ];
    kernelParams = [
      "8250.nr_uarts=11"
      "console=ttyAMA10,9600"
      "console=tty0"
    ];
    kernel.sysctl = {
      "net.ipv4.ip_forward" = 1;
      "net.ipv6.conf.all.forwarding" = 1;
    };
  };

  hardware = {
    bluetooth.enable = true;
    raspberry-pi.config = {
      pi5 = {
        dt-overlays = {
          vc4-kms-v3d-pi5 = {
            enable = true;
            params = { };
          };
        };
      };
      all = {
        base-dt-params = {
          krnbt = {
            enable = true;
            value = "on";
          };
        };
      };
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS_SD";
    fsType = "ext4";
  };

  fileSystems."/boot/firmware" = {
    device = "/dev/disk/by-label/FIRMWARE";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/mnt/wd500" = {
    device = "/dev/disk/by-uuid/6bf02424-40c6-4966-9fb1-9d5d2b071a8a";
    fsType = "ext4";
    options = [
      "nofail"
      "rw"
    ];
  };

  fileSystems."/mnt/evo970" = {
    device = "/dev/disk/by-uuid/f0895f54-b1fb-4406-9c55-eeb12e4822d7";
    fsType = "ext4";
    options = [
      "nofail"
      "rw"
    ];
  };

  raspberry-pi-nix.board = "bcm2712";

  swapDevices = [ ];

  networking = {
    interfaces.wlan0.useDHCP = lib.mkDefault true;
    useDHCP = lib.mkDefault true;
  };

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
