on:
  workflow_dispatch:
    inputs:
      skip-schedule-steps:
        description: "Skip update steps normally run on schedule"
        type: boolean
        default: false
  schedule:
    - cron: "30 1 * * *"
permissions: {}
name: Build and cache NixOS configuration
jobs:
  build-and-cache:
    name: "Build server configurations and push to Attic"
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: quasar
            runner: ubuntu-latest
            cache: x86_64-linux
            public-key: "x86_64-linux:XrBbCCueC9hO05zf8GjmK1/YtHuZwqwcgx0pkHWLgvM="
          - target: vortex
            runner: ubuntu-24.04-arm
            cache: aarch64-linux
            public-key: "aarch64-linux:n1uEEJsd/qjPYB1G3jUEW1oyia8O9rTCJKpCLgPW2gM="
          - target: zenith
            runner: ubuntu-24.04-arm
            cache: aarch64-linux
            public-key: "aarch64-linux:n1uEEJsd/qjPYB1G3jUEW1oyia8O9rTCJKpCLgPW2gM="
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Create disk space
        if: "${{ matrix.runner == 'ubuntu-latest' }}"
        uses: wimpysworld/nothing-but-nix@dd6ef566962bfa4656301706035da97ebbe90e9b # v9
        with:
          hatchet-protocol: rampage
          witness-carnage: true

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Nix and Attic
        uses: ./reusable-workflows/setup-nix-cache
        with:
          attic-cache: ${{ matrix.cache }}
          attic-public-key: ${{ matrix.public-key }}
          attic-endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          attic-token: ${{ secrets.ATTIC_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update nixpkgs
        if: "${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && !inputs.skip-schedule-steps) }}"
        shell: bash
        run: nix flake update nixpkgs

      - name: Build NixOS configuration
        shell: bash
        env:
          TARGET: ${{ matrix.target }}
        run: nix build --print-build-logs ".#nixosConfigurations.${TARGET}.config.system.build.toplevel"

      - name: Push to attic cache
        shell: bash
        run: |
          attic push --jobs 1 --filter '^((steam|appimage)-(run|fhs)(-run)?|(google-chrome|nvidia|android-studio|firefox-nightly-bin).*)$' "${CACHE}" ./result
        env:
          CACHE: ${{ matrix.cache }}
