on:
  workflow_dispatch:
    inputs:
      skip-schedule-steps:
        description: "Skip update steps normally run on schedule"
        type: boolean
        default: false
  schedule:
    - cron: "0 2 * * 1"
permissions: {}
name: Build and cache NixOS configuration
jobs:
  build-and-cache:
    name: "Build server configurations and push to Attic"
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: quasar
            runner: ubuntu-latest
          - target: vortex
            runner: ubuntu-24.04-arm
          - target: zenith
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    env:
      ATTIC_CACHE: main
      ATTIC_PUBLIC_KEY: "main:NJFT3TW7YUy7Ee3HPnkx3FS3Hw3N4OYidsOF/3A12Do="
    steps:
      - name: Create disk space
        if: "${{ matrix.runner == 'ubuntu-latest' }}"
        uses: wimpysworld/nothing-but-nix@dd6ef566962bfa4656301706035da97ebbe90e9b # v9
        with:
          hatchet-protocol: rampage
          witness-carnage: true

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Nix and Attic
        uses: ./.github/reusable-workflows/setup-nix-cache
        with:
          attic-cache: ${{ env.ATTIC_CACHE }}
          attic-public-key: ${{ env.ATTIC_PUBLIC_KEY }}
          attic-endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          attic-token: ${{ secrets.ATTIC_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update nixpkgs
        if: "${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && !inputs.skip-schedule-steps) }}"
        shell: bash
        run: nix flake update nixpkgs

      - name: Build NixOS configuration
        shell: bash
        env:
          TARGET: ${{ matrix.target }}
        run: nix build --print-build-logs ".#nixosConfigurations.${TARGET}.config.system.build.toplevel"

      - name: Push to attic cache
        shell: bash
        run: |
          attic push --jobs 1 \
            --filter '(?i)^((steam|appimage)-(run|fhs)(-run)?|(nvidia|open-webui|ollama|n8n|cuda|libcublas|clang|rustc|nerd-fonts).*)$' \
            "${ATTIC_CACHE}" \
            ./result
