name: Check docker compose services
on: push
jobs:
  file-changes:
    runs-on: ubuntu-latest
    outputs:
      any: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            docker/**/*.yml
            docker/*.yml
  run-services:
    needs: [file-changes]
    runs-on: ubuntu-latest
    if: needs.file-changes.outputs.any == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Check docker compose services
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: "./docker/docker-compose.yml"
