name: Nix Build

on:
    push:
    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    file-changes:
        runs-on: ubuntu-latest
        outputs:
            any: ${{ steps.changed-files.outputs.any_changed }}
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "recursive"
                  fetch-depth: 0

            - name: Check changed files
              id: changed-files
              uses: tj-actions/changed-files@v35.9.1
              with:
                  files: |
                      flake.nix
                      nixos/*.nix
                      nixos/**/*.nix

    wsl-check:
        needs: [file-changes]
        runs-on: ubuntu-22.04
        if: needs.file-changes.outputs.any == 'true'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Nix
              uses: cachix/install-nix-action@v19

            - name: Run nix check
              shell: bash
              run: nix build .#homeConfigurations.wsl.activationPackage

    intelbox-check:
        needs: [file-changes]
        runs-on: ubuntu-22.04
        if: needs.file-changes.outputs.any == 'true'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Nix
              uses: cachix/install-nix-action@v19

            - name: Run nix check
              shell: bash
              run: nix build .#homeConfigurations.intelbox.activationPackage
