ntfy-settings: ENC[AES256_GCM,data:eLS9f9q/IjAVqUxlivHmxB9fPv1Y/i4N1bA+49atzXzrQB7hcsA/IELcse3h5hiQdfRQNFxG0INi4EQF7zHw85fqyQSPtA==,iv:GtINaDmnC7nuLmEe5m8jX+n1InVHJS9kxl0ARjUJE3U=,tag:5dEKlvOo2cmVWjcy/OOIFQ==,type:str]
sops:
    age:
        - recipient: age1nn5xascw770dyjnga00ptpy3nuxuhunygajkekdaa7sjfx74msss63crpw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWkxJdlVYeHJBOTUySlVW
            aU1ZR0FFd3VJT1c2Z29jeW1RdWIwR0QvNnhVCjBNYVhuM1lpSXJtMkk4a1dEQzhR
            MTMxYTJRbWl1dEhEeC9zOWxadnA3Um8KLS0tIFpLcTA4VmFWNUlnT0hRS1BqWUtt
            ZlBEN2Y4bFdNaDdmRWFEeDZ0UkNMMWsKBoZHiKR+AWnJxVn6Hh8PqoTdSui8NkAx
            OOQenBsNgdgc0G3SxUg25NOEgd3NeQkP9/q4K7bDDBARGauCbDyiMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mchyxdcsrxqly8esmfa8d3urgq99kae25e6kn606v6dt6r7z7v7q8ezly5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOczEwWGlWcC9IL292cU5x
            M0pwdEJVRkhDUk92WTFyWVJRSUx5RkJQVXpVCjRRVmNXWFp5Y1ZuZWNKbERkUnhP
            RC9ESjEyS3lxVko5QTVWQ3N0S3JoL0UKLS0tIFBmSVVNbFZ2cXRlSS9qa3hjNTB6
            M25wNW5WYzBmQnU5cHhBOGozZC9iNUUKC3Mw+/TNIREiu4aac8IbeEHqJk+jwtcO
            9GgYUgNKqMJffRhxXA4jpcFMmkhfFs31cO92tHthdOhNiIjXOfzfLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yq2ksala2xds5jd626yqqt84uyuzetmknpyyemn7nuvgv4jdmy3s95ewwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYXRUVjhQbFlKcjZ0bWZw
            RGlZOWhsekNYOHJySFBaRDBkUWhyd0g4eWprClVPSlpJa1hyWk5SSmdzajRWbkpj
            and5MmxDc2NvV094RXhzNVNLY08xYm8KLS0tIHdkdWY3YnorbkM0MFdKM2xMUDhx
            K1FKTVlvU0MvL0xFZldGT2hUM2ZFK1kK5JKb5abYdMrO/pvqTEGLr3rNBYmILcD9
            13ixd+Ovd6XTHPMKMWJHA72ILEvHWarm86dxGjIoK6ENFDPpZ60a9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1shggmz7tt4uc0jucrn42gnu5mtwd7rmumw70k4xw0xj7wmps3yxqarmy97
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNURLanRhU2JlUU8rVzBn
            NmQxU3F3NVdhdUNhcFZvYmxDRithK0tPSFY0CjBYVEdkK0RpUWlpeGovVi90RkQz
            WVlqcGJtWUhYYUxBdUxta21MUjFIN2cKLS0tIGRma3dudWczdkRSdkh1ZGZxVllX
            U2RiVFpFQ09abkNmUEFlRzJwMUNVTDQKC0hKuBGr/9PhYDaPn+/GWgg13DAwIax+
            eMeO+hHym/9/qzgqDhRLcIWEwO6ACizWB63QDUMYrz7UMs3nK7U4vQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xp8ekv8t7fuqgm8uet6sr9a308pgj6wpry4jwcr904rz8s8vyffs424xph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VUFyeE1WMFZkMVc5YkRi
            VkthRTBMZ3JvZUxsRUxVQXlVRDVFY0pzSGc0CmFnS3BLNDRXd1VWcXIzN3QxMDNq
            THlCZWZDeVJnME5nbDc3WU9qMnkySzAKLS0tIFZLU2h3dmw0MXI5N1lsdUdWM3M3
            NlU5NnBPVjM0VXpxa3M3WmZReFlIQTAKzOiKQlEykApUTrPXEBwG04fzOnj0NWb+
            KzkrCAAvOlAZhqye3gC68lZmUG2UAMK3vq1BQemnHdj8xVrD9fzsrQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tq6tucepu9pmqp5r6xhtj0lrzpa836ud3szzpt9nsn57cpxw9fksdw235r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TTZaeDFLNlQ1NUhhMFc5
            ZjNhMFRxVjZhZVhnTlFuV0o3MGdpTDIycTBVCnpsOFpOOW90VmZCbis3U3lOVVEy
            OVl4UXRiL2huRlBHZ2dFRWNaTDN1R2cKLS0tIFQzSkhDRlBUT2lMNzdsN0ZvQjlE
            bXdVQ3dVM20vbXdrdjhhNllKaE80OHcKw7x5GgZq6ERZj8hMrDGT9mP4qDigOMhs
            8SHRhlv6V2FWBT+gCqy9JIXKaD16aqI6xfiPNavopWxHCbMzMvRcmg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17qlc0x0mltj3l2dqwag3dtf5jxzvftvmfkl5a386y3fsxdh49pgqrdqd7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBckt6eGlCSjlrU0w5aGlY
            aVhVTDVPRXFJN2NKNnRFUkgzdFVHeHUvTVJNClBOVktDYWpGNjZFdmJLQTRTdTQ1
            L3dvcWFkeWFTYmFZRGl3V1FCVE9sUDQKLS0tIHVvQWZuVVlxa00rYjVQREF2dVVU
            dUtXVmdPSWNTUDFLcXB5MnVKeEo4Q0UKMjyyJ1wQgI6bKBti+z7DIOz+Zkqx9l2P
            VzAFOBGW7irgFfkMyveWFaHLOjW3DpwXj4bNBKaVIorJyQyihREcNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-07T15:29:41Z"
    mac: ENC[AES256_GCM,data:2FiPzsfvbX67QFmE+2wjKAyGy1fi2h6oii3KZ1uvywkOecUW4sjfWc5cq3zxhOQlygWtONN6mFaw4FNJNJsd6WqIOaErSI0rPLK+bTaxH2uqijX/FsJ4mVTXW5gEgelfqnbUcCYfGrRM842YhNxsdTRPFo9jpFCsugy3gUak3Ys=,iv:Z4Csh4yjRLxUc9gshKYJmASFJKLGlrObgOTZTXypoJo=,tag:42RFzrZuMuIaeWfcHrBm5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
