ntfy-settings: ENC[AES256_GCM,data:eLS9f9q/IjAVqUxlivHmxB9fPv1Y/i4N1bA+49atzXzrQB7hcsA/IELcse3h5hiQdfRQNFxG0INi4EQF7zHw85fqyQSPtA==,iv:GtINaDmnC7nuLmEe5m8jX+n1InVHJS9kxl0ARjUJE3U=,tag:5dEKlvOo2cmVWjcy/OOIFQ==,type:str]
sops:
  age:
    - recipient: age1nn5xascw770dyjnga00ptpy3nuxuhunygajkekdaa7sjfx74msss63crpw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOFk0TFplSnpIUkdjaUYr
        OW5sb01MeDBLdGplUGJCMVI0ajZyb2lrbkJZCkVFYy9oSm5Yd1hRdndzQXRyVXVJ
        dkZGdEZFL1ZMdlFQRHgyaDF6MTFEYzAKLS0tIHg5ZjZkZXFhRmIxMDMxUk5nUGlL
        dzVpc21FS1FOTjcrS1pvRG5MdmhaVjAKxyRi5RggCxXaEmHpaSTB2oRredT75OxN
        cW5ytbjtwwh2oywkqLQGjLskUlslF0VDcYHLJpSr80ImRdPHk4a7yg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1mchyxdcsrxqly8esmfa8d3urgq99kae25e6kn606v6dt6r7z7v7q8ezly5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNE0yZThsMzdoN1pHSjV5
        T25oRC9wS3JRYTVPN0tWc01vT3dpZktuTHpBCmloaTBEUnBqQlhNcDZvcENJZWRj
        amNJK1liSWRiL2VoNWZUYkFNZ3I1SVUKLS0tIEU5TzhrdWZqTExjU2srb0s0blpB
        T21URVd2UWFhYTBxVHZLQUdSczhraDQKxhHF092FmbinZFEf53RZdqUCahyxl+8K
        nNSWXghnswiOfrfld7uZ1d6JqtIcCPI+pQ4lPGN4Q/rnpe63qw6eFA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1yq2ksala2xds5jd626yqqt84uyuzetmknpyyemn7nuvgv4jdmy3s95ewwa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WThjQjhTTysvdDRuTlRZ
        RVpJbUg0NWo5TGc5RFVUMVV2U0k5M3hXQzI0CnBzYjh2TEpxSVNVOVlUaDhPUUFX
        R0tQNXhVTDlIaDBmTkhneHh3T1pUeEUKLS0tIEhPbHZZNEVwVFB1dEhpVC81R2NK
        cnZ4V1V5Zk9UbnpOWFMxVlJTWkJlYjgK3VYG3N9uRQcKI9EmNv7iwJ5wBDMZecAS
        m5KvrC2grd5dbz8uYdOTqNIQbo4i7IeVYRN0B32PFKmFwrKRgKpRiQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1shggmz7tt4uc0jucrn42gnu5mtwd7rmumw70k4xw0xj7wmps3yxqarmy97
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZkxSK0VHTkF2TkYzV3R6
        VXA0Zjh1RmxCZ3M4akFCSEZUcDJFbTBrNEJNCjVKYU4zeFVJUzJJbE5wcTAwbFNk
        ZEtJMVlNQTh1WHZNZnlnRjh5eG5BckkKLS0tIExNcmREendMUTJFYlpGUDV2bjNS
        cmZaeWllS2sveGNrWEw3d1A3VHArancK5yXnveiEaecxJNQI9L1FfEEBMzNc5WuJ
        TG4wOwOuO7oGcw4FXHjqBWeFvEq1trrPiLXF/b4gc2DowEhEJ8ZOsw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1xp8ekv8t7fuqgm8uet6sr9a308pgj6wpry4jwcr904rz8s8vyffs424xph
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGejEyUy84R2t2N1YzVC94
        WTY2VlVVV3FTTVVQbFFoM3djcEZDMzlkR1hrClNuaDR1MlBDUGRpemJBVkI2NWxr
        bnJhV0ZQRVhvaFU5bUdlUnZUT083ZWsKLS0tICs4dDN1QUQ5VWs1ckZBNzlTSjg2
        M3YyZ2ZKTTF0OVhWT3lxa2JFckhxdWcKrIRLtpz9GzhAl9zjgSh9oUfu7jgfZ5Uc
        SXod1PaHz+AiUwbQSAaPn6XMwwXOZInr80/1t5utmTvJMWJK0jfHTw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17qlc0x0mltj3l2dqwag3dtf5jxzvftvmfkl5a386y3fsxdh49pgqrdqd7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArc2VRWC84VS9OOW5sR0tM
        c1NiNzJMWWNOSWhVYU8vTktYZlFoTGZBaW1ZCjBjaStXR0ZtbmRNdjNmYVR5NEN5
        VzQyYkNsa05HVDRKZWNOcWlBZXFhU28KLS0tIGJsK2VlZ1gzWlJWRkhDTzVQWS9S
        T2Rwbk5KN3Y4QnRRZWkwR2Y1UzJ4NnMKy6Q8yWLXmjgmdUd9gnVhwZ1ThhgzpeBg
        x7LdbisEoadftOh3akN4ZVr0rtPp5xJWbQpYBNJIyfkO4kykDEOdpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-07T15:29:41Z"
  mac: ENC[AES256_GCM,data:2FiPzsfvbX67QFmE+2wjKAyGy1fi2h6oii3KZ1uvywkOecUW4sjfWc5cq3zxhOQlygWtONN6mFaw4FNJNJsd6WqIOaErSI0rPLK+bTaxH2uqijX/FsJ4mVTXW5gEgelfqnbUcCYfGrRM842YhNxsdTRPFo9jpFCsugy3gUak3Ys=,iv:Z4Csh4yjRLxUc9gshKYJmASFJKLGlrObgOTZTXypoJo=,tag:42RFzrZuMuIaeWfcHrBm5g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
