ntfy-settings: ENC[AES256_GCM,data:eLS9f9q/IjAVqUxlivHmxB9fPv1Y/i4N1bA+49atzXzrQB7hcsA/IELcse3h5hiQdfRQNFxG0INi4EQF7zHw85fqyQSPtA==,iv:GtINaDmnC7nuLmEe5m8jX+n1InVHJS9kxl0ARjUJE3U=,tag:5dEKlvOo2cmVWjcy/OOIFQ==,type:str]
sops:
    age:
        - recipient: age1nn5xascw770dyjnga00ptpy3nuxuhunygajkekdaa7sjfx74msss63crpw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVDNEZ1cwUTJqYnE4akJ5
            dDRmVmwvb1FWdmRvRWFVeGVveTViN2RkcUJjCkxnK2dSOWh4TlM0bmdwam12V3cr
            aVRjMkZzNFNpblluZDU2a1MwODBvYncKLS0tIEIxb3FMd3hHQ09GMVJxaEZqNTdP
            OXVMQW0wdTFMZFc3Tm1ZWjRhY3k5UDAKWYbvE5VgJcrTr7qtMkpD/FdhH3937RiP
            sN54z6LZ8rxdGIxyEQl9r/fEELX7pVLUWyhDgNTKgL1GpUUkjGdJiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mchyxdcsrxqly8esmfa8d3urgq99kae25e6kn606v6dt6r7z7v7q8ezly5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZXkwU0V6d2NCY2JFSFJI
            eFN0amZpUFFHb0NyTWxVd1k3U3pjeCtFblFvCnYzUXhKMVdqK283R2plOGQ1WUx4
            Ukc1OWNlMU1rSnZmS3lEYmJCcHZoSTgKLS0tIENPZ1kvOXZTNExsenBtT0J1Q1JO
            dlVXck1tVFl5S3RHQS9va0U2ZVdHUWcKJVkd4zICnxn47d8EqjE1AddP+SnLmB5G
            MxG6ZUJe6oUYLnmRGNegAvftcoFWobp2LAwmt8Imoe8UK5PWUWjl1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yq2ksala2xds5jd626yqqt84uyuzetmknpyyemn7nuvgv4jdmy3s95ewwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUmJRUXhkd3pIY1hTanhR
            eDc0bmNHL3BMNFdlWitjUUxFN1dSMXg0TlRBCmdhYWFqTXhyVktxNUQzV1JseVBE
            MklBSGEyd3hKVjJ1TFN0MEJMSUJWYzQKLS0tIG00VnQybGVwQzM4d0pmZVljTVNQ
            QmNJZnlBRHJNdUszN3UzdmRLanpUdGcKaNjVp1AUuPC/SucF777mE2BQkWAzJbpx
            yaMoM9LmX91hoVwDZ98a0NdJhziIkcMdEBWY64OHlraxH6BmpiZmNA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1shggmz7tt4uc0jucrn42gnu5mtwd7rmumw70k4xw0xj7wmps3yxqarmy97
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTL3UzeTRZVFdkWkk2QTlZ
            YkdGODBsRmxOMXJCd29JbW54THZvVjJkOGhrCjVNSHIwRWU2T0l0ZnR2RnJwQ0sx
            ckE0NnhYZ2Z5Q25CcW5QeFlUdnVxOFUKLS0tIGhqM2JJczVVTS9zWnhDclJ6bjQv
            RW9WU1o4Y21EZ0FXMStJaUo1cHBsVU0Kip//QtegSMKpOCNISvXMFP9NixP58hkv
            ws2feefqB9n2iF9q5DM1v5RKiL//TOoVMDB+JMuKHtXCCgoMLqdozQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xp8ekv8t7fuqgm8uet6sr9a308pgj6wpry4jwcr904rz8s8vyffs424xph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RG9BTVUrcC8xQ28wTWxh
            UTFmVjdmcm1tTGpvaXpzbVRYcEFXOEJhS2hBCjZ3T2tqZVVWOUFUZGR4YW1zS2xE
            cmIzbHQzM0pwcWhIMkd3bzJvVDJ2Q1UKLS0tIGpnWUlHem5qUW9wWUlCeFZKZEdV
            bDQ1ZmcvN21SMUlpb2NKOE85Q0dqL2cKr2xrNOjkyDa9F7Mv5KbvcFbZYARlLYJh
            HjjpzZGAw6o2CLRUCwFQuY6hctaLiIvfEX2c+1f4Aw2WJH50IHSQjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1406ysxk30mwkpdnts88qdengk9en0nw7l0sah2g97zldush5admqgtlgex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwakxQVndSZFc2ai9lSTZm
            Q3AzeENCRndNNUFzb3VHWVRHclc1aFd2SVRnCkc0K1BvdWdQbUJCRGxwKzJTRm1C
            ajcwRHRNR012VjFUWXlOdEpPdllMdU0KLS0tIEk5NFhreDlpTjJsZFhmZyswem9l
            NVduTG5oUkY5eTBpREdDT09TdlNBYTQKPojfUo5W/rfOEgZOReBTtUwlnmfdNvyP
            g04YNPp1OViXy/uHhpaZMW6En/3NkDd+woYR/IlrRLZoE4vdq7weCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17qlc0x0mltj3l2dqwag3dtf5jxzvftvmfkl5a386y3fsxdh49pgqrdqd7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaanMyRGU2SitMVTMxRFlY
            OVJIeHJFenRzNDlJbUxWT1JhSml3VXJFa0RRCjVqYm1KWnlPZlQ2ekpoTXg5Vnll
            cUY3YU1XU1lOSUo3TVFNRDVjZ2dMTW8KLS0tIEVMN1craExFUkhTbWxOYkI3aWZo
            M3FDU2djVXArUS8xR3dLWmV1QW16YUUKkzXovyVzolT/v2mnPbQ3KUyRoG9+XL+M
            Hw1gNeFClhu1TgA9/yhaQbgqi5hu2kgynPNOZjPxltrDtqVTsHceSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-07T15:29:41Z"
    mac: ENC[AES256_GCM,data:2FiPzsfvbX67QFmE+2wjKAyGy1fi2h6oii3KZ1uvywkOecUW4sjfWc5cq3zxhOQlygWtONN6mFaw4FNJNJsd6WqIOaErSI0rPLK+bTaxH2uqijX/FsJ4mVTXW5gEgelfqnbUcCYfGrRM842YhNxsdTRPFo9jpFCsugy3gUak3Ys=,iv:Z4Csh4yjRLxUc9gshKYJmASFJKLGlrObgOTZTXypoJo=,tag:42RFzrZuMuIaeWfcHrBm5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
