crowdsec_api_key: ENC[AES256_GCM,data:6RnnTQDIhOJFowG3VCjV7O76Czj07G4Z6Da4yIWhVPC4OpeYJWm3sDsuRA==,iv:GHPKto4YJaurFqn1OIxKjQ1c1ppRwTwSG0dp8YSG0Ww=,tag:Ac48dqq61/YvG0OxFPQBYA==,type:str]
sops:
    age:
        - recipient: age1nn5xascw770dyjnga00ptpy3nuxuhunygajkekdaa7sjfx74msss63crpw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQTZnYXcrNUVlanN1ZDhh
            Y2ZrdlZ4bTYyQWs0aVlweHJDVG5TeUVqOFdVCm9jejBLM2o4UUxxSFdxa3ZDOXEx
            YWd2aUJOb1hrSFprZURLbk5OWUNkWVEKLS0tIGJvYWE4TUFCYUtueWVmVW9kRDNW
            NjQ2UWtISW5RaGlYdUZtdzA3U3ZHbjQKFwyrt5YnCuu13cX1/NymCXK1euEt1yTs
            PaVpwFfRrQ/n2fBKZZM384vKdBQV+smvf1vZTXf44u4sQUL9u0Z7Iw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mchyxdcsrxqly8esmfa8d3urgq99kae25e6kn606v6dt6r7z7v7q8ezly5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TTF4Q29CbnRZQUhObkZB
            cjZSL3JROTVCNG5RMkUvbVREeEZPRW9CQXlZCkpIUStsdHBWLzVCUWZsNkFHdWJX
            a1VoQWg2SGFLY2VVN0Z5OUg3Mk1xSnMKLS0tIFJld3RTcktkeUZFWUZoV0M4enc4
            MHVxSTI0b2pNQWNjVCs5eDFDcEg3dmsKR40IbccJIeOerPEHLkBXswRlavivUCoO
            bg3D6wd1xZwLPCK5z16gxsxgKkTi4HLPiUnqqQH32WSlR0c3PKKbOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yq2ksala2xds5jd626yqqt84uyuzetmknpyyemn7nuvgv4jdmy3s95ewwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMnY2YUpRWFFPVXcwREtk
            dlhGdzlJT2paOGxsUmdJbWVadkVhT3FvNFUwCjVNMVRnSW41VlVHUjZlOFdrS1Yz
            bEtlVFpYK3BmVTJkQjNhUWEvRWhnK2MKLS0tIDgyc2hoZ1BKV2syZTZUOHY2b0sv
            YmpyYWo4V1BsdkhEM1JoSTl5L0J2NTgKbFFXi+aa6LlmKYMpv0SwulgzubRrGT+m
            zf6f8gJa8cDiJQsU8B2SOyrdk573XitxwkdT1kX+ONyGlLilGeGFkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1shggmz7tt4uc0jucrn42gnu5mtwd7rmumw70k4xw0xj7wmps3yxqarmy97
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmb1BLZytwbVVRMm1vSkpD
            QW43amE2NUlZNDQyaXVaQ2RHV01CNlp6U0d3ClJ1UDliU1JuSlJIUE13K1FrZlls
            VldkSEM1YVRoMGhrNTdYbm0rZ2JhL3cKLS0tIGpzaHpkL0FybVVrUW5FRmtScGdx
            U0h0MmlJbEtpR20xTUJYaUtNcVJxemsK4VDa/wpUlGWBxe4/HtzV0iVDfeZcABUi
            CQAeG4Kvd1LvLmVX5e2U9kXyVX1IB15+phorDrOenwe0pNYq/bFHWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xp8ekv8t7fuqgm8uet6sr9a308pgj6wpry4jwcr904rz8s8vyffs424xph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYmcvZG45V05JWjFzc2Rk
            SkgxbHVHeXYyUjIxZythMHFxa0JkNVovMEc4CjE5WUtZR21nMDZPd1JvOTZyRDNa
            L1kxVWpyemRVUnRQa1NTQkNDcFlLUEEKLS0tIC9XTEtvNVZHUStLTWtIU3NMY2Js
            SmtNeWFPTnBnekd4K2F2QzBENy9vS0EKNuvmJ00yuAM8KfvBeZEBOEo84qeWXRhs
            UajhyFuiq17bbwsEpajYfCERGplZTjtJ8k7/KnIITqNKjX6oaiYC7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tq6tucepu9pmqp5r6xhtj0lrzpa836ud3szzpt9nsn57cpxw9fksdw235r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcVZlRG1Mam1yeGRHVDl2
            bVRDbDJwc2ZBQ2pzdSszSklSM3NWWkhBdjNJCm9PRWpXMG1TQmQ5RmpML0hHSi9D
            RXhLVEN1ZVRuR3djTWZMQ3JrSVJVMUUKLS0tIHBoeUNxZXlIWXZBWVp2a2NLd3ht
            QzA2SXVaVGs2cDFxKzhQbFU0bkRLOFUKKrIuftuHLuLURWvo2ufrevisOqLbMnkL
            vprG81JWxiG2hCEGLkBv6lDdB2F2BmvlY14KMS7IsbruRyfkRoZqBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17qlc0x0mltj3l2dqwag3dtf5jxzvftvmfkl5a386y3fsxdh49pgqrdqd7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOTZTMVYxSEdVdUNRbndZ
            VGJQUjU1UXU4Y21Ra0NNZ0MxYWJIdlZjWFdBCnpUNFRsUjRNN0FWMHhCaDBQUmdU
            L0tqL3MvL1AzWFdEdC9MVXRlWFZNQU0KLS0tIGV3QUZ0MWdVTEtGY3lpU2lCaElv
            clJHQSt1cmdoSHZpVUJSaXdXd2pUaTAKcgQeXDx8SddPxc2royX1LyfZR510mX2s
            LTmOyrqmjWlJWNP9qhkRtrFdT9PnJlI8dGtZvW5kx1U7bzpSf93e7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T18:39:21Z"
    mac: ENC[AES256_GCM,data:KyVd10aJBM/lP1vedILGrldlkWDytH9M66PZYaxIo3NeC+dNOJ3f6Ey1GZHdri1KNBph84NSL+DmflCJ28HwA2/OA6bxMzzc9XEjC9ee0rmzosvNLvM8coIEa7Rxf/nS/IyyA5uFjN/naY2+/RaYR/fSwZSbn1Xlk/Y7N1QuVL0=,iv:cWCmFjSPk70aVSIoMu3ienozsbJPbJEfUIz/9bopdU8=,tag:XesV4vQZE2I8eVpcod0QmQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
