crowdsec_api_key: ENC[AES256_GCM,data:6RnnTQDIhOJFowG3VCjV7O76Czj07G4Z6Da4yIWhVPC4OpeYJWm3sDsuRA==,iv:GHPKto4YJaurFqn1OIxKjQ1c1ppRwTwSG0dp8YSG0Ww=,tag:Ac48dqq61/YvG0OxFPQBYA==,type:str]
sops:
  age:
    - recipient: age1nn5xascw770dyjnga00ptpy3nuxuhunygajkekdaa7sjfx74msss63crpw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YjZacDVia1pSbCtRREZw
        QlFDaUpuZzFkYmJMT1ZtUW9mY0dwczhaUnpVCnhiSUxpbVZmVG85aDk0SGsvRkNa
        WDNkeVVKVUZnVjhBMlJ5TkhLSVZ0MkkKLS0tIHVLUVgzSUU2QzU2UFFUQ2FXRUVs
        cjY0Mks5MC93MTVLYVZqOExYTFptZ3MK0xlpTVcz0RGtpz3NemC5t2c2jzf9LoJl
        vStuE6NJA7WHw1j4RF7JAjl0/9nM+R6EhRZLFixxIMF/w2oz1vnrRg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1gjpkkr3vp8xaswzmnywl9zalkgja3v6y3eqy4rthk2nxdssvk3lq6gsfsl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpLzM2dFJxaUltSHo5aXhx
        ZU85ZU5hNEZock9wRE96WGR1eHNEZGJRNWtBCkxGV25FTFBVejV5bGpsZFYxQ2NC
        b1lpN09UWU1hUHB4V2xTYlZkUDNFY0UKLS0tIHpjaDZaRTBWNTFvem5xVEJDWVhF
        aVFJSzFMTWdDM1NMMk1KdnBaWDFvemsKE2d0Ae2M10FVoMBVlECkeBPclo4hap6e
        nzEW1iug/GGS434kl2KlILGjyrsA6NCWgmd9PvfyPkKOhICxgD+xqA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1mchyxdcsrxqly8esmfa8d3urgq99kae25e6kn606v6dt6r7z7v7q8ezly5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdzZhT0VzajBxTzM5M05l
        Vmcxd0J3STR2WkZ5aE1DaWd6M0pMcDkxL2k0Cnk1bDNyaEk5b2hacTh4QjRPTjV6
        VVBlNjRxOXNYcXhpS3I4UHFSNnRpMjgKLS0tIFZzY0wycGhyN1V3NzdmM3MyeGVy
        ZzFEU3NYbk5LT2U0ODRIMlJRc2dyNUkKhj8+kZucuNc842RW4hcoFUrqDJQ5y49x
        Bfli2HdrlixlYdHfEvvD6HfMZ4YR8VQ3XGJ2QAq6iMAs3N/9ivtIyw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1yq2ksala2xds5jd626yqqt84uyuzetmknpyyemn7nuvgv4jdmy3s95ewwa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYXJUbVEwMk1Ob2xlYUJu
        aXpyM3JUMVE3OFliZXIrRjBmeUI0QzZKTmdVClNCd2xQV01WV0U1NzJFREhlSldY
        Vk83UElsblIvOWxHV1pnYUlocm0yckUKLS0tIFB5VzJDUkY5NGF6MXkrdW95Vmhw
        QVZHVEsxZnpaRTZRTUtMampLSURZaDQKsjLEd4GzTBqqJO+9LUlwpNQJJ7GiMojc
        swu4aY8a38z8BX7t7K1IV/B0meVpBtWS8qgxjGIToqxj1mgR8dm/Ow==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1shggmz7tt4uc0jucrn42gnu5mtwd7rmumw70k4xw0xj7wmps3yxqarmy97
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzlBK3N3OU9PZERJN2Vu
        NTZpSG03RFBoRVdhVEdsWXFqQzNxQTdpTVJ3CmdyemlPZzdZSmE2NDd3eFBlbTRq
        RjN6d0ZWZlZDQXltMGlyeVBYMmlJVlEKLS0tIEg2RE5NVFluWmNUSjlneHFnQ2wy
        a3I5eEs5UUkzaXZ1bXJWL0l0VEFmNVUKNuaQlmx6wnbAAVzaLGrXoGH+1MNyiAlF
        62YEtXKeNphm19yj5OL0ptJ1h9tW7Ot+LVsbKvn9L7W1tylX0ib+og==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1xp8ekv8t7fuqgm8uet6sr9a308pgj6wpry4jwcr904rz8s8vyffs424xph
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVWJtTTQ1T0xKVTZsbDBW
        djg2ZmtnL0IvbzFtRk1TcEx3b2NQOEM4OFhjCnlpZkVPS3JTYWNTMitSUVByYUhU
        SFZPSTZ6M3NwT1Y0dDN6eXhpMEdtd3MKLS0tIE5oZlVTOHVjbWZYVEZNakdxUUpH
        Ry95ODRDQ1BPUVdrUXduZTJFTkRtNm8K3W8Rrh/5VTZgvW8NTL4MnQCsKG7irgRb
        YRJrmsSX8VPKVf8Kp4Em2R9Mwcsrltme/SWHIwLmWpJK2uycZ3DFyA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1tq6tucepu9pmqp5r6xhtj0lrzpa836ud3szzpt9nsn57cpxw9fksdw235r
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cmhLcmU0emFkTjBvcVIr
        ZHlVZkRvN1RIZDNYaGF0UEZlZ1FtU1hlVzNVClZyTmdlNXZhc1lmam1jTUd2dEpB
        S0pvc1g0bnZPZDFvVG5UQytCT0JPakEKLS0tIDRNOXlndXVRQmpXcUdKRUFtdm9S
        MkpPdjN4bVczRFkySGphb3RSN2NiamcKpYF84gkV0w2vN4hKxI6r/KraR1FEM0HM
        KwDbnK03GBvR8XhJUVE+Ns177LClzzBIcdt3BzcYe1OjCkhUMO35eg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17qlc0x0mltj3l2dqwag3dtf5jxzvftvmfkl5a386y3fsxdh49pgqrdqd7z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLL001T2Q0SlNUVlY3VHpp
        dWpGQVd5NGNxeUEzSVlqUHovOXphdWpYVzFRCmIyVFBhbExDMEU2dW9jdzBOMXdx
        VndiWW90cFVGeXk4eGhRbGpMYWlZSG8KLS0tIDVpOU5icWszeUlUMWFpOFE5ZkVF
        TmY0RUZRYTBNUnprNFlFcjF5d1ZOVlUK/bLI2Zl0Zf7iKXfLYQBGCHDhPwrQAlJU
        oFNMyDOiu0J8K/R4cUFtQvgWxZl9LyvkSVsObkaOieEFPFlK/Vn+CQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T18:39:21Z"
  mac: ENC[AES256_GCM,data:KyVd10aJBM/lP1vedILGrldlkWDytH9M66PZYaxIo3NeC+dNOJ3f6Ey1GZHdri1KNBph84NSL+DmflCJ28HwA2/OA6bxMzzc9XEjC9ee0rmzosvNLvM8coIEa7Rxf/nS/IyyA5uFjN/naY2+/RaYR/fSwZSbn1Xlk/Y7N1QuVL0=,iv:cWCmFjSPk70aVSIoMu3ienozsbJPbJEfUIz/9bopdU8=,tag:XesV4vQZE2I8eVpcod0QmQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
